GET http://localhost:5000

Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxsbGxzZHNkc0BnbWFpbC5jb20iLCJpZCI6IjY1NjM1ZjViYTZiZDlkODE1MWM0ODA4ZSIsImlhdCI6MTcwMTAxNjA1OX0.W-cESC8hKFjZj8HokxH-nIi_GmbXl0qQa4xrlG3m3Xk


###
GET http://localhost:5000/111



###
# Register 
POST http://localhost:5000/auth/register
Content-Type: application/json

{
    "email":"llllsdsds@gmail.com",
    "password":"sdsdsdsjadas"
}


###
# Login 
POST http://localhost:5000/auth/login
Content-Type: application/json

{

    "email":"llllsdsds@gmail.com",
    "password":"sdsdsdsjadas"
}

###
POST http://localhost:5000/auth/refresh-token

{"ref_token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImxsbGxzZHNkc0BnbWFpbC5jb20iLCJpZCI6IjY1NjM1ZjViYTZiZDlkODE1MWM0ODA4ZSIsImlhdCI6MTcwMTA5Njg1MCwiZXhwIjoxNzMyNjU0NDUwfQ.h1cyBphv3Jujm53cDHmOus4-mjtB2rsxp4kKjviKOIA"
   
}
###
DELETE  http://localhost:5000/auth/logout





####
GET http://localhost:5000/api/items

###
POST http://localhost:5000/api/createItem
Content-Type: application/json

{
    "name":"pen",
    "description":"to write",
    "price":3.99,
    "product_id":1,
    "userId":"65635f5ba6bd9d8151c4808e"
}

